# Generated by Django 3.2.13 on 2022-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesPDF',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('agency', models.CharField(db_column='Agency', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('pdf_name', models.CharField(db_column='PDF_Name', max_length=255)),
                ('date', models.DateField(db_column='Date')),
                ('last_update_date', models.DateField(db_column='Last_Update_Date')),
            ],
            options={
                'db_table': 'MATCHES_PDF',
                'managed': False,
            },
        ),
    ]
